# Generated by Django 3.1.2 on 2020-11-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ola',
        ),
    ]
