# Generated by Django 3.1.2 on 2020-10-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20201027_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
