# Generated by Django 3.1.2 on 2020-11-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alumne_profe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
